### ISSUE TITLE
Error: authentication required but no callback set

### ISSUE THREAD

**Issue by chan-dev** [larscom/ng-chrome-extension#16] opened 2021-07-18 04:20 UTC
I've installed the tool but executing it throws an error. 
My nodejs version is v12.22.1
![ng-chrome-issue](https://user-images.githubusercontent.com/46891115/126055537-e2429daa-ba13-4ed7-ace7-eeeff64a9ae5.png)

**Comment by larscom** [comment] 2021-07-18 08:28
Hi, do you still have this issue?
I can't reproduce with version 12.22.1 of node.

What is your OS?

**Comment by chan-dev** [comment] 2021-07-18 23:04
Yup, I still having the issue. I'm on Xubuntu 20.04

**Comment by larscom** [comment] 2021-07-19 07:42
can you try update @larscom/ng-chrome-extension to v2.0.4 and see if it works.

**Comment by chan-dev** [comment] 2021-07-20 00:20
tried updating and reinstalling but still the problem persists

**Comment by larscom** [comment] 2021-07-20 09:15
Do you get the same error when you clone any open source project from github? Like the tool itself? (git clone https://github.com/larscom/ng-chrome-extension.git)

**Comment by chan-dev** [comment] 2021-07-20 09:22
do you mean just the **git clone** action itself? If so, no i don't get any error

**Comment by larscom** [comment] 2021-09-05 09:40
Have you managed to find the problem? Else ill close this issue

**Closed** 2021-09-12 22:27 UTC
